fields = {
	faq_category = {
		label = FAQ category,
		description = Group heading on the home page such as Accessing or Use Credits Citations,
		width = 600px,
		height = 1
	},
	faq_question = {
		label = FAQ question,
		description = Question displayed on the accordion button,
		width = 600px,
		height = 1
	},
	faq_answer = {
		label = FAQ answer,
		description = Answer with paragraphs and links,
		usewysiwygeditor = 1,
		width = 600px,
		height = 300px
	},
	title = {
		label = Page title,
		description = Title of page,
		
		width = 600px,
		height = 1
	},
	bodytext = {
		label = Page text,
		description = Main text for page,
		
		usewysiwygeditor = 1,
		width = 600px,
		height = 300px
	}
}
